### ISSUE TITLE
Invalid content format

### ISSUE THREAD

**Issue by tobymaro** [marklogic-community/newrelic-plugin#24]
Env:
  Marklogic 8.0-4
  newrelic-plugin 0.2.8
  Python 2.7.12
  requests (2.14.2)

Looks like plugin itself connects to Marklogic. But cant send info to New Relic.

```
execute http post call
Invalid content format
```

**Comment by hansenmc** [comment]
Version 0.3.0 has been released and should resolve any invalid content format issues previously encountered.
