### ISSUE TITLE
ERROR 'int' object has no attribute '__getitem__' with MarkLogic 9.0-8.2

### ISSUE THREAD

**Issue by hansenmc** [marklogic-community/newrelic-plugin#27]
Unable to run the plugin against MarkLogic 9.0-8.2. 

Seeing errors that look like:

```
newrelic_marklogic plugin now sending statuses to NewRelic Plugin API (to see more log messages change log_level=DEBUG).
retrieve statuses and update newrelic
dereference http GET
http://localhost:8002/manage/v2?view=status&format=json
'int' object has no attribute '__getitem__'
retrieve statuses and update newrelic
dereference http GET
http://localhost:8002/manage/v2?view=status&format=json
'int' object has no attribute '__getitem__'
```
In another environment, the error message was for `float` instead of `int`:

    ERROR 'float' object has no attribute '__getitem__'

It seems that this is because of newly added fields and differences in the https://docs.marklogic.com/REST/GET/manage/v2@view=status response. 

Newly added fields, such as `memory-process-huge-pages-size`, `memory-process-res`, `memory-size`, `memory-system-free`, `memory-system-total`, `total-cpu-stat-system`, `total-cpu-statu-user`

are returned as primitive numeric values. 

    "memory-size": 16384

However, most of the other metrics are returned as objects that have `units` and `value` properties. Such as:

```
"total-hosts": { 
  "units": "quantity",
  "value": 6
}
```

It seems that adjustments need to be made to the following places in __init__.py to accommodate these newer properties with primitive values, instead of expecting that they will be objects that have a `value` property.

I think we could change lines like:
```
                else:
                    metrics["Component/hosts/" + metric + "[" + host_summary[metric]["units"] + "]"] = \
                        host_summary[metric]["value"]
```
to:
```
                    val = host_summary[metric]
                    if type(val) is dict:
                        metrics["Component/hosts/" + metric + "[" + host_summary[metric]["units"] + "]"] = val["value"]
                    else:
                        metrics["Component/hosts/" + metric + "[quantity]"] = val
```
in the following locations:
- https://github.com/marklogic-community/newrelic-plugin/blob/master/newrelic_marklogic_plugin/__init__.py#L172
- https://github.com/marklogic-community/newrelic-plugin/blob/master/newrelic_marklogic_plugin/__init__.py#L202
- https://github.com/marklogic-community/newrelic-plugin/blob/master/newrelic_marklogic_plugin/__init__.py#L228

If that sounds reasonable, I can submit a PR with those changes.

**Comment by laquereric** [comment]
Please consider tagging a new release that includes this fix. This will allow users to both deploy tagged releases and use this plugin with MarkLogic 9.0-8.2.
