### ISSUE TITLE
Connection error causes system.exit

### ISSUE THREAD

**Issue by hansenmc** [marklogic-community/newrelic-plugin#33]
If any exception other than `Timeout` or `TooManyRedirects` is encountered, the default behavior is to log the exception and then invoke `sys.exit(1)` and terminate.

I have observed the following error logged before terminating:
> 2019-05-03 04:04:49,777 newrelic_marklogic_plugin.http_utils ERROR    ('Connection aborted.', BadStatusLine("''",))

Rather than terminating, the desired behavior for these unsuccessful requests would have been to log the error and then simply retry after the configured seep duration.

Consider changing `http_utils.py` to expand the list of request exceptions that can be handled without killing the application.

Maybe something like this:

        except (requests.ConnectTimeout, 
                requests.HTTPError, 
                requests.ReadTimeout, 
                requests.Timeout, 
                requests.ConnectionError) as exception:
            log.error(exception)
        except requests.exceptions.RequestException as e:
            log.error(e)
            sys.exit(1)

**Comment by xquery** [comment]
added you to admins for this repo -  I still would recc using your fork to apply commits but now you should be able to merge.
