### ISSUE TITLE
New Relic Plugin EOL - Wednesday, June 16th, 2021

### ISSUE THREAD

**Issue by grtjn** [marklogic-community/newrelic-plugin#40]
See https://discuss.newrelic.com/t/new-relic-plugin-eol-wednesday-june-16th-2021/127267

**Comment by hansenmc** [comment]
Yes, plugins are going away. I have been working with one client to build out a solution using the New Relic flex agent. They plan to post an example yml file to demonstrate how to configure various Manage API calls to fetch metrics and post to New Relic under https://github.com/newrelic/nri-flex/tree/master/examples

**Comment by grtjn** [comment]
That was suggested to us (SensingClues) as well, we'd be interested..

**Comment by grtjn** [comment]
@hansenmc are you including telemetry logs in the new approach? Seems to be a (relatively) new feature. I came across this video, but unsure if it is up to date: https://developer.marklogic.com/video/telemetry-and-new-relic/

**Comment by hansenmc** [comment]
Telemetry sends info to MarkLogic, not New Relic. The New Relic stats collected and sent by the plugin are what is available from the Manage REST API. I'm not aware of a means of also sending telemetry to third party (and not sure that it would be recommended or supported).

The MarkLogic New Relic Integration examples were just merged into the nri-flex project https://github.com/newrelic/nri-flex/pull/299

**Comment by grtjn** [comment]
Ah, penny drops.. Telemetry is to help ML Support monitor MarkLogic instances. Thanks for the link to nri-flex!

**Comment by grtjn** [comment]
@hansenmc feedback on the digest example. It is using curl --anyauth, which causes curl to make two calls to first detect auth method, and then make the actual call with correct method. Works well if you are in doubt whether it is basic or digest, but if you Know it is digest, using --digest is faster..

**Comment by hansenmc** [comment]
You should comment (or submit a PR) to https://github.com/newrelic/nri-flex
